### ISSUE TITLE
Help links direct to Electron as opposed to My Budget

### ISSUE THREAD

**Issue by iGondor** [reZach/my-budget#1]
Help -> About/Documentation/Community Discussion/Search Issues all direct to Electron as opposed to here

![image](https://user-images.githubusercontent.com/40286648/55936374-5689d480-5c60-11e9-8024-d77f267a3559.png)

**Comment by reZach** [comment]
As noted in the PR, the following json object needs to be updated as well such that non-Mac menus behave the same as Mac menus: https://github.com/reZach/my-budget/blob/a9b1a39e253f1f6f11c7569ed26fde9043f9850f/app/menu.js#L242

**Comment by reZach** [comment]
Fixed in https://github.com/reZach/my-budget/releases/tag/v1.0.4-beta. Closing.
