### ISSUE TITLE
new user hover cutoff 

### ISSUE THREAD

**Issue by zaydons** [reZach/my-budget#5]
**Describe the bug**
When hovering over the "new user?" button on the main screen, the text box that appears is cut off. 

**To Reproduce**
1. go to main screen.
2. hover over "new user?" button

**Expected behavior**
My hope would be to read the rest of the text.. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9087799/57115870-6a849b80-6d1f-11e9-8c45-e6d81b753096.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Release Version: 2.1.0-beta (2.1.0-beta.20190425.1)

**Comment by reZach** [comment]
Thanks @zaydons, I have a pending fix for this in the next release.

**Comment by reZach** [comment]
@zaydons Fixed as of https://github.com/reZach/my-budget/releases/tag/v3.0.0-beta
