### ISSUE TITLE
Feature: Monthly income schedule

### ISSUE THREAD

**Issue by Lerentis** [reZach/my-budget#7]
Hi there,
your application looks far better than any other solution i have seen in the lase few month, so thank you already for that. do you thin it might be possible to add a montly schedule option for income or even better some logic like "+ amount x every y days"?

**Comment by reZach** [comment]
Thank you, by the way!

@Lerentis What use case would you consider **y** to be? Every day? Does that include weekends? Holidays?

**Comment by Lerentis** [comment]
Just a fix number of days that the user can enter to repeat events

**Comment by Trigger1235** [comment]
meets speak I don't?

**Comment by Trigger1235** [comment]
hi``

**Comment by Trigger1235** [comment]
deatjstar
deathstar
yayvh CVC

**Comment by reZach** [comment]
@Trigger1235 if you continue this spam, you will be blocked from this repository. This is your final warning.
@Lerentis thank you for clarifying.

**Comment by reZach** [comment]
@Lerentis a few more days and this feature will be in.

**Comment by Lerentis** [comment]
Awsome, thanks :D

**Comment by reZach** [comment]
@Lerentis This has been added in this version [v3.2.0-beta](https://github.com/reZach/my-budget/releases/tag/v3.2.0-beta). Thanks for opening this issue and bringing new features to users.

Closing this issue.

**Comment by reZach** [comment]
A [new version](https://github.com/reZach/my-budget/releases/tag/v3.2.1-beta) fixes an issue with "income every 'x' days".
