### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by maiph** [reZach/my-budget#9]
There are lots of inconsistencies around code formatting.
Also when i open the project in vscode after `npm i` i get errors from eslint all over the project.

Are there any plans to clean up the project and fix those issues?

**Comment by reZach** [comment]
Hi @maiph, thanks for showing interest in the project.

That is exactly one of the things that is on my to-do list, I'm planning on doing that after I write up support to drag and drop/re-order categories and sub-categories.

**Comment by maiph** [comment]
I'll be looking forward for that change then.

**Comment by reZach** [comment]
@maiph the drag-n-drop is getting moved back for the time being. Our first lint run is here (more to come):
https://github.com/reZach/my-budget/commit/57b7709841e7cd31a3cab7984c90f05460ec8fc8

**Comment by reZach** [comment]
@maiph the repo is now linted (error-free), as well as a Azure Pipelines CI build has been set up that runs `npm run lint` on commits to **master** and for PRs. The status of the latest build can be found on the README (updated) [here](https://github.com/reZach/my-budget).

I do still want to go through and refactor the code, that will come soon. Closing this issue - thanks for asking for this issue to get the conversation started.
